platform: ios, '11.0'
use_frameworks!

#platform :ios, '9.0'

target 'EasySwiftUIKit_Example' do
  pod 'EasySwiftUIKit', :path => '../'

  target 'EasySwiftUIKit_Tests' do
    inherit! :search_paths

    
  end
end
